cart/urls.py
from django.urls import path
from . import views


app_name = 'cart'
urlpatterns = [
  path('', views.cart_summary, name='cart_summary'),
  path('add/', views.cart_add, name='cart_add'),
  path('delete/', views.cart_delete, name='cart_delete'),
  path('update/', views.cart_update, name='cart_update'),
]

ecom/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('', include('store.urls')),
    path('cart/', include('cart.urls')),
    path('admin/', admin.site.urls),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

store/urls.py
from django.urls import path
from . import views


app_name = 'store'
urlpatterns = [
    path('', views.home, name='home'),
    path('login/', views.login_user, name='login'),
    path('logout/', views.logout_user, name='logout'),
    path('register/', views.register_user, name='register'),
    path('product/<int:pk>', views.product, name='product'),
    path('category/<slug:slug>', views.category, name='category'),
]

store/models.py
from django.db import models


class Category(models.Model):
    name = models.CharField(
        max_length=50,
        unique=True
    )
    slug = models.SlugField()

    def __str__(self) -> str:
        return self.name

    class Meta:
        verbose_name_plural = 'Categories'


class Customer(models.Model):
    first_name = models.CharField(
        max_length=50,
        verbose_name='First name'
    )
    last_name = models.CharField(
        max_length=50,
        verbose_name='Last name'
    )
    phone = models.CharField(
        max_length=15,
        verbose_name='Phone'
    )
    email = models.EmailField(
        max_length=100,
        verbose_name='Email'
    )
    password = models.CharField(
        max_length=100,
        verbose_name='Password'
    )

    def __str__(self) -> str:
        return f'{self.first_name} {self.last_name}'

    class Meta:
        verbose_name_plural = 'Customers'


class Product(models.Model):
    name = models.CharField(
        max_length=100,
        verbose_name='Name'
    )
    price = models.DecimalField(
        decimal_places=2,
        max_digits=6,
        verbose_name='Price'
    )
    category = models.ForeignKey(
        to=Category,
        on_delete=models.CASCADE,
        default=1,
        verbose_name='Category'
    )
    description = models.TextField(
        default='',
        blank=True,
        null=True,
        verbose_name='Description'
    )
    image = models.ImageField(
        upload_to='uploads/product',
        verbose_name='Image'
    )
    is_sale = models.BooleanField(
        default=False,
        verbose_name='Is on sale'
    )
    sale_price = models.DecimalField(
        decimal_places=2,
        max_digits=6,
        blank=True,
        null=True,
        verbose_name='Sale price'
    )
    

    def __str__(self) -> str:
        return self.name

    class Meta:
        verbose_name_plural = 'Products'


class Order(models.Model):
    product = models.ForeignKey(
        to=Product,
        on_delete=models.CASCADE,
        verbose_name='Product'
    )
    customer = models.ForeignKey(
        to=Customer,
        on_delete=models.CASCADE,
        verbose_name='Customer'
    )
    quantity = models.IntegerField(
        default=1,
        verbose_name='Quantity'
    )
    address = models.CharField(
        max_length=200,
        verbose_name='Address'
    )
    phone = models.CharField(
        max_length=15,
        default='',
        blank=True,
        null=True,
        verbose_name='Phone'
    )
    date = models.DateField(
        auto_created=True,
        verbose_name='Date'
    )
    status = models.BooleanField(
        default=False,
        verbose_name='Status'
    )

    def __str__(self) -> str:
        return f'{self.product} - {self.customer}'

    class Meta:
        verbose_name_plural = 'Orders'

store/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User


class SignUpForm(UserCreationForm):
    email = forms.EmailField(
        label='',
        widget=forms.TextInput(
            attrs={'class':'form-control', 'placeholder':'Email address'},
        )
    )
    first_name = forms.CharField(
        label='',
        max_length=50,
        widget=forms.TextInput(
            attrs={'class':'form-control', 'placeholder':'First name'},
        )
    )
    last_name = forms.CharField(
        label='',
        max_length=50,
        widget=forms.TextInput(
            attrs={'class':'form-control', 'placeholder':'Last name'},
        )
    )

    class Meta:
        model = User
        fields = ('username', 'first_name', 'last_name', 'email', 'password1', 'password2')
    
    def __init__(self, *args, **kwargs):
        super(SignUpForm, self).__init__(*args, **kwargs)

        self.fields['username'].label = ''
        self.fields['username'].widget.attrs['class'] = 'form-control'
        self.fields['username'].widget.attrs['placeholder'] = 'Username'
        self.fields['username'].help_text = '<span class="form-text text-muted"><small>Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.</small></span>'
        
        self.fields['password1'].label = ''
        self.fields['password1'].widget.attrs['class'] = 'form-control'
        self.fields['password1'].widget.attrs['placeholder'] = 'Password'
        self.fields['password1'].help_text = '<ul class="form-text text-muted small"><li>Your password can\'t be too similar to your other personal information.</li><li>Your password must contain at least 8 characters.</li><li>Your password can\'t be a commonly used password.</li><li>Your password can\'t be entirely numeric.</li></ul>'
        
        self.fields['password2'].label = ''
        self.fields['password2'].widget.attrs['class'] = 'form-control'
        self.fields['password2'].widget.attrs['placeholder'] = 'Confirm password'
        self.fields['password2'].help_text = '<span class="form-text text-muted"><small>Enter the same password as before, for verification.</small></span>'

store/views.py
from django.contrib import messages
from django.contrib.auth import authenticate, login, logout
from django.shortcuts import get_list_or_404, get_object_or_404, redirect, render
from .forms import SignUpForm
from .models import Category, Product


def home(request):
    products = Product.objects.all()
    categories = Category.objects.all()[:5]
    return render(
        request, 'store/home.html',
        {'products': products, 'categories': categories,}
    )

def login_user(request):
    if request.user.is_authenticated:
        return redirect('store:home')

    categories = Category.objects.all()[:5]
    if request.method == 'POST':
        username = request.POST['username']
        password = request.POST['password']
        user = authenticate(request, username=username, password=password)
        if user is not None:
            login(request, user)
            messages.success(request, message='Welcome!')
            return redirect('store:home')
        else:
            messages.error(request, message='Wrong username or password. Try again.')
            return render(request, 'store/login.html', {'categories':categories,})
    else:
        return render(request, 'store/login.html', {'categories':categories,})

def logout_user(request):
    logout(request)
    return redirect('store:home')

def register_user(request):
    form = SignUpForm()
    categories = Category.objects.all()[:5]
    if request.method == 'POST':
        form = SignUpForm(request.POST)
        if form.is_valid():
            form.save()
            username = form.cleaned_data['username']
            password = form.cleaned_data['password1']
            user = authenticate(username=username, password=password)
            login(request, user)
            messages.success(request, 'You have been registered! Welcome!')
            return redirect('store:home')
        else:
            messages.error(request, 'There was an error registering you. Please try again.')
            return redirect('store:register')
    return render(request, 'store/register.html', {'form': form, 'categories':categories,})

def product(request, pk):
    product = get_object_or_404(Product, pk=pk)
    categories = Category.objects.all()[:5]
    return render(request, 'store/product.html', {'product': product, 'categories':categories,})

def category(request, slug):
    category = get_object_or_404(Category, slug=slug)
    products = get_list_or_404(Product, category=category)
    categories = Category.objects.all()[:5]
    return render(
        request, 'store/home.html',
        {'products': products, 'categories': categories,}
    )

store/templates/store/home.html
{% extends "base.html" %}
{% block content %}
<!-- Header -->
<header class="bg-dark py-5">
  <div class="container px-4 px-lg-5 my-5">
    <div class="text-center text-white">
      <h1 class="display-4 fw-bolder">Shop in style</h1>
    </div>
  </div>
</header>
{% for message in messages %}
<div class="alert alert-{{ message.tags }} alert-dismissible fade show" role="alert">
  {{ message }}
  <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
</div>
{% endfor %}
<section class="py-5">
  <div class="container px-4 px-lg-5 mt-5">
    <div class="row gx-4 gx-lg-5 row-cols-2 row-cols-md-3 row-cols-xl-4 justify-content-center">
      {% for product in products %}
      <div class="col mb-5">
        <div class="card h-100">
          {% if product.is_sale %}
          <!-- Sale badge -->
          <div class="badge bg-dark text-white position-absolute" style="top: 0.5rem; right: 0.5rem">Sale</div>
          {% endif %}
          <!-- Product image -->
          <img class="card-img-top" src="{{ product.image.url }}" alt="..." />
          <!-- Product details -->
          <div class="card-body p-4">
            <div class="text-center">
              <!-- Product name -->
              <h5 class="fw-bolder">{{ product.name }}</h5>
              <!-- Product price -->
              {% if product.is_sale %}
              <span class="text-muted text-decoration-line-through">${{ product.price }}</span>
              </br>${{ product.sale_price }}
              {% else %}
              ${{ product.price }}
              {% endif %}
            </div>
          </div>
          <!-- Product actions -->
          <div class="card-footer p-4 pt-0 border-top-0 bg-transparent">
            <div class="text-center"><a class="btn btn-outline-dark mt-auto" href="{% url 'store:product' product.id %}">View product</a></div>
          </div>
        </div>
      </div>
      {% endfor %}
    </div>
  </div>
</section>
{% endblock content %}

store/templates/store/login.html
{% extends "base.html" %}
{% block page_title %}{{ block.super }} | Login{% endblock page_title %}
{% block content %}
<!-- Header -->
<header class="bg-dark py-5">
  <div class="container px-4 px-lg-5 my-5">
    <div class="text-center text-white">
      <h1 class="display-4 fw-bolder">Login</h1>
      <p class="lead fw-normal text-white-50 mb-0">Enter your credentials</p>
    </div>
  </div>
</header>
</br></br></br>
<div class='container col-4 text-center'>
  <div class="row justify-content-center">
    {% for message in messages %}
    <div class="alert alert-{{ message.tags }} alert-dismissible fade show" role="alert">
      {{ message }}
      <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    </div>
    {% endfor %}
    </br>
    <form method="post" action="{% url 'store:login' %}">
      {% csrf_token %}
      <div class="mb-3">
        <input type="text" class="form-control" name="username" placeholder="Username">
      </div>
      <div class="mb-3">
        <input type="password" class="form-control" name="password" placeholder="Password">
      </div>
      <button type="submit" class="btn btn-primary">Login</button>
    </form>
  </div>
</div>
</br></br></br>
{% endblock content %}

store/templates/store/product.html
{% extends 'base.html' %}
{% block title %}{{ block.super }} | {{ product.name }}{% endblock title %}
{% block content %}
<section class="py-5">
  <div class="container px-4 px-lg-5 my-5">
    <div class="row gx-4 gx-lg-5 align-items-center">
      <div class="col-md-6">
        <img class="card-img-top mb-5 mb-md-0" src="{{ product.image.url }}" alt="..." />
      </div>
      <div class="col-md-6">
        <div class="small mb-1">{{ product.category }}</div>
        <h1 class="display-5 fw-bolder">{{ product.name }}</h1>
        <div class="fs-5 mb-5">
        {% if product.is_sale %}
          <span class="text-decoration-line-through">${{ product.sale_price }}</span>
        {% endif %}
          <span>${{ product.price }}</span>
        </div>
        <button class="btn btn-primary" type="button" data-bs-toggle="offcanvas" data-bs-target="#offcanvasRight" aria-controls="offcanvasRight">Product description</button>
        <div class="offcanvas offcanvas-end" tabindex="-1" id="offcanvasRight" aria-labelledby="offcanvasRightLabel">
          <div class="offcanvas-header">
            <h5 class="offcanvas-title" id="offcanvasRightLabel">Description</h5>
            <button type="button" class="btn-close" data-bs-dismiss="offcanvas" aria-label="Close"></button>
          </div>
          <div class="offcanvas-body">
            {% for paragraph in product.description.splitlines %}
            <p>
              {{ paragraph }}
            </p>  
            {% endfor %}
          </div>
        </div>
        <br/><br/>
        <br/><br/>
        <div class="d-flex">
          <input class="form-control text-center me-3" id="inputQuantity" type="num" value="1" style="max-width: 3rem" />
          <button class="btn btn-outline-dark flex-shrink-0" type="button" value="{{ product.id }}" id="add-cart">
            <i class="bi-cart-fill me-1"></i>
            Add to cart
          </button>
        </div>
      </div>
    </div>
  </div>
</section>
<script>
  $(document).on("click", "#add-cart", function(e){
    e.preventDefault();
    $.ajax({
      type: "POST",
      url: "{% url 'cart:cart_add' %}",
      data: {
        product_id: $("#add-cart").val(),
        product_qty: $("#inputQuantity").val(),
        csrfmiddlewaretoken: "{{ csrf_token }}",
        action: "post"
      },
      success: function(json){
        document.getElementById("cart_quantity").innerText = json.qty;
      },
      error: function(xhr, errmsg, err){
        
      }
    });
  })
</script>
{% endblock content %}
  

store/templates/store/register.html
{% extends "base.html" %}
{% block page_title %}{{ block.super }} | Register{% endblock page_title %}
{% block content %}
<!-- Header -->
<header class="bg-dark py-5">
  <div class="container px-4 px-lg-5 my-5">
    <div class="text-center text-white">
      <h1 class="display-4 fw-bolder">Register</h1>
      <p class="lead fw-normal text-white-50 mb-0">New here?</p>
    </div>
  </div>
</header>
</br></br>
<div class='container col-4 text-center'>
  <div class="row justify-content-center">
    {% for message in messages %}
    <div class="alert alert-{{ message.tags }} alert-dismissible fade show" role="alert">
      {{ message }}
      <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    </div>
    {% endfor %}
    </br>
    <form method="post" action="{% url 'store:register' %}">
      {% csrf_token %}
      {{ form.as_p }}
    </br>
    <button type="submit" class="btn btn-secondary">Register</button>
    </form>
  </div>
</div>
</br></br>
{% endblock content %}