cart/urls.py
from django.urls import path
from . import views


app_name = 'cart'
urlpatterns = [
  path('', views.cart_summary, name='cart_summary'),
  path('add/', views.cart_add, name='cart_add'),
  path('delete/', views.cart_delete, name='cart_delete'),
  path('update/', views.cart_update, name='cart_update'),
]

ecom/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('', include('store.urls')),
    path('cart/', include('cart.urls')),
    path('admin/', admin.site.urls),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

store/urls.py
from django.urls import path
from . import views


app_name = 'store'
urlpatterns = [
    path('', views.home, name='home'),
    path('login/', views.login_user, name='login'),
    path('logout/', views.logout_user, name='logout'),
    path('register/', views.register_user, name='register'),
    path('product/<int:pk>', views.product, name='product'),
    path('category/<slug:slug>', views.category, name='category'),
]

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="pt-BR">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
    <meta name="description" content="" />
    <meta name="author" content="" />
    <title>{% block page_title %}e-Com{% endblock page_title %}</title>
    <!-- Favicon -->
    <link rel="icon" type="image/x-icon" href="{% static 'assets/favicon.ico' %}" />
    <!-- Bootstrap icons -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.5.0/font/bootstrap-icons.css" rel="stylesheet" />
    <!-- Core theme CSS (includes Bootstrap) -->
    <link href="{% static 'css/styles.css' %}" rel="stylesheet" />
    <script src="https://code.jquery.com/jquery-3.7.1.min.js" integrity="sha256-/JqT3SQfawRcv/BIHPThkBvs0OEvtFFmqPF/lYI/Cxo=" crossorigin="anonymous"></script>
  </head>
  <body>
    <!-- Navigation -->
    {% include "navbar.html" %}
    <!-- Section -->
		{% block content %}{% endblock content %}
    <!-- Footer -->
    <footer class="py-5 bg-dark">
      <div class="container"><p class="m-0 text-center text-white">Copyright &copy; e-Com 2023</p></div>
    </footer>
    <!-- Bootstrap core JS -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js"></script>
    <!-- Core theme JS -->
    <script src="{% static 'js/scripts.js' %}"></script>
  </body>
</html>

templates/navbar.html
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <div class="container px-4 px-lg-5">
    <a class="navbar-brand" href="{% url 'store:home' %}">e-Com</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation"><span class="navbar-toggler-icon"></span></button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0 ms-lg-4">
        <li class="nav-item"><a class="nav-link active" aria-current="page" href="{% url 'store:home' %}">Home</a></li>
        {% if user.is_authenticated %}
        <li class="nav-item"><a class="nav-link" href="{% url 'store:logout' %}">Logout</a></li>
        {% else %}
        <li class="nav-item"><a class="nav-link" href="{% url 'store:login' %}">Login</a></li>
        <li class="nav-item"><a class="nav-link" href="{% url 'store:register' %}">Register</a></li>
        {% endif %}
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" id="navbarDropdown" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">Categories</a>
          <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
            <li><a class="dropdown-item" href="#">All Categories</a></li>
            <li><hr class="dropdown-divider" /></li>
            {% for category in categories %}
            <li><a class="dropdown-item" href="{% url 'store:category' category.slug %}">{{ category.name }}</a></li>
            {% endfor %}
          </ul>
        </li>
      </ul>
      <form class="d-flex">
        <a href="{% url 'cart:cart_summary' %}" class="btn btn-outline-dark">
          <i class="bi-cart-fill me-1"></i>
          Cart
          <span class="badge bg-dark text-white ms-1 rounded-pill" id="cart_quantity">{{ cart|length }}</span>
        </a>
      </form>
    </div>
  </div>
</nav>